version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  backup:
    build: .
    # image: simple2b/pg-backup:1.0
    links:
      - db
    volumes:
      - ./backup:/backup
    environment:
      SCHEDULE_HOUR: ${SCHEDULE_HOUR:-"*"}
      SCHEDULE_MINUTE: ${SCHEDULE_MINUTE:-"*"}
      SCHEDULE_SECOND: ${SCHEDULE_SECOND:-"*"}
      SCHEDULE_YEAR: ${SCHEDULE_YEAR:-"*"}
      SCHEDULE_MONTH: ${SCHEDULE_MONTH:-"*"}
      SCHEDULE_DAY: ${SCHEDULE_DAY:-"*"}
      SCHEDULE_WEEK: ${SCHEDULE_WEEK:-"*"}
      SCHEDULE_DAY_OF_WEEK: ${SCHEDULE_DAY_OF_WEEK:-"*"}
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 7
      S3_REGION: ${S3_REGION:-**None**}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      S3_BUCKET: ${S3_BUCKET:-**None**}
      S3_PREFIX: ${S3_PREFIX:-**None**}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      AWS_DEFAULT_REGION: ${S3_REGION:-**None**}

volumes:
  db_data:
