# example of docker compose file that could be used on production
version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  backup:
    image: simple2b/pg-backup:latest # set version
    links:
      - db
    volumes:
      - ./backup:/backup
    environment:
      # scheduler
      SCHEDULE_HOUR: ${SCHEDULE_HOUR:-0}
      SCHEDULE_MINUTE: ${SCHEDULE_MINUTE:-0}
      SCHEDULE_SECOND: ${SCHEDULE_SECOND:-0}
      SCHEDULE_YEAR: ${SCHEDULE_YEAR:-0}
      SCHEDULE_MONTH: ${SCHEDULE_MONTH:-0}
      SCHEDULE_DAY: ${SCHEDULE_DAY:-0}
      SCHEDULE_WEEK: ${SCHEDULE_WEEK:-0}
      SCHEDULE_DAY_OF_WEEK: ${SCHEDULE_DAY_OF_WEEK:-0}
      SCHEDULE_START_DATE: ${SCHEDULE_START_DATE:-**None**}
      SCHEDULE_END_DATE: ${SCHEDULE_END_DATE:-**None**}
      DAYS_HISTORY: 7
      # PG
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_EXTRA_OPTS: "--schema=public --blobs"
      # S3
      S3_REGION: ${S3_REGION:-**None**}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      S3_BUCKET: ${S3_BUCKET:-**None**}
      S3_PREFIX: ${S3_PREFIX:-**None**}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-**None**}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-**None**}
      AWS_DEFAULT_REGION: ${S3_REGION:-**None**}
      # google cloud storage
      GCS_BUCKET: ${GCS_BUCKET:-**None**}
      GCS_PREFIX: ${GCS_PREFIX:-backup}

volumes:
  db_data:
